# Continuous Integration config
# travis-ci.org
#
# see http://about.travis-ci.org/docs/user/build-configuration/
#

language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev
  - pypy
  
group: travis_latest

git:
  depth: 3


# command to install dependencies
install:
  - pip install -e .[tests]

# command to run tests
script: 
  - pytest -rsv
  - flake8

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]] then
    coverage run --source=tinytag $(command -v pytest)
    coveralls;
    fi
